[package]
name = "swap"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/swap.rs"

[dev-dependencies]
num-bigint = "0.4.2"

[dependencies.elrond-wasm]
version = "0.35.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.35.0"
